import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "react-calendar/dist/Calendar.css";
import "react-datepicker/dist/react-datepicker.css";
import { Toaster } from "react-hot-toast";
import "react-image-crop/dist/ReactCrop.css";
import "./globals.css";
import QueryClientProvider from "./query-client-provider";
import OauthProviders from "./oauth-provider";
import { Suspense } from "react";
import GlobalLoading from "@/components/global-loading";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Talentz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.variable}>
      <body>
        <Suspense fallback={<GlobalLoading />}>
          <OauthProviders>
            <QueryClientProvider>
              <Theme>
                {children}
                <Toaster />
              </Theme>
            </QueryClientProvider>
          </OauthProviders>
        </Suspense>
      </body>
    </html>
  );
}
